spring.datasource.sqlScriptEncoding: UTF-8
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:../customer;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    hibernate.ddl-auto: validate
  thymeleaf.cache: false



